/* eslint-disable no-unused-vars */
// The data here is from https://us.agworld.co/user_api/v1/docs => Simulated Response, with some copy+paste+modifications

export function getCompanyForUserID(userId, setCompany) {
  setTimeout((userId) => {
    // console.log(`This is a stub for getting Company data. It ignored the userID (${userId})`);
    setCompany({
      id: '987124',
      type: 'companies',
      links: { self: 'http://example.org/user_api/v1/companies/987124' },
      attributes: {
        business_identifier: '124',
        business_structure: null,
        company_type: 'Farmer',
        contact_email: 'farmer.jim@farmingproductions.com',
        contact_name: 'Farmer Jim',
        created_at: '2011-06-15T10:30:00.000+08:00',
        description: null,
        name: 'Farming Productions',
        physical_location: {
          number: null,
          street: null,
          suburb: null,
          city: null,
          county: null,
          state: null,
          postcode: null,
          country: 'Australia',
          latitude: -29.0779350143255,
          longitude: 133.664062768221,
        },
        postal_location: {
          number: null,
          street: null,
          suburb: null,
          city: null,
          county: null,
          state: null,
          postcode: null,
          country: null,
          latitude: null,
          longitude: null,
        },
        state_name: null,
        account_number: '12345678',
        updated_at: '2011-06-15T10:30:00.000+08:00',
      },
      relationships: {
        activities: {
          links: {
            self: 'http://example.org/user_api/v1/companies/987124/relationships/activities',
            related: 'http://example.org/user_api/v1/companies/987124/activities',
          },
        },
        farms: {
          links: {
            self: 'http://example.org/user_api/v1/companies/987124/relationships/farms',
            related: 'http://example.org/user_api/v1/companies/987124/farms',
          },
        },
        seasons: {
          links: {
            self: 'http://example.org/user_api/v1/companies/987124/relationships/seasons',
            related: 'http://example.org/user_api/v1/companies/987124/seasons',
          },
        },
      },
    });
  }, 200 + 1000 * Math.random());
}

export function getFarmsForCompanyID(companyId, setFarms) {
  setTimeout((companyId) => {
    // console.log(`This is a stub for getting Farms data. It ignored the companyID (${companyId})`);
    setFarms({
      987613: {
        id: '987613',
        type: 'farms',
        links: { self: 'http://example.org/user_api/v1/farms/987613' },
        attributes: {
          company_id: 987124,
          created_at: '2011-06-15T10:30:00.000+08:00',
          description: 'Home Farm',
          location: {
            number: null,
            street: null,
            suburb: null,
            city: null,
            county: null,
            state: 'Western Australia',
            postcode: null,
            country: 'Australia',
            latitude: -29.0779350143255,
            longitude: 133.665562768221,
          },
          name: 'Farm 1',
          reporting_region: 'Farm 1',
          updated_at: '2011-06-15T10:30:00.000+08:00',
        },
        relationships: {
          company: {
            links: {
              self: 'http://example.org/user_api/v1/farms/987613/relationships/company',
              related: 'http://example.org/user_api/v1/farms/987613/company',
            },
          },
          fields: {
            links: {
              self: 'http://example.org/user_api/v1/farms/987613/relationships/fields',
              related: 'http://example.org/user_api/v1/farms/987613/fields',
            },
          },
        },
      },
      987614: {
        id: '987614',
        type: 'farms',
        links: { self: 'http://example.org/user_api/v1/farms/987614' },
        attributes: {
          company_id: 987124,
          created_at: '2011-06-15T10:30:00.000+08:00',
          description: 'Orchard',
          location: {
            number: null,
            street: null,
            suburb: null,
            city: null,
            county: null,
            state: 'Western Australia',
            postcode: null,
            country: 'Australia',
            latitude: -29.0779350143255,
            longitude: 133.665562768221,
          },
          name: 'Farm 1',
          reporting_region: 'Farm 1',
          updated_at: '2011-06-15T10:30:00.000+08:00',
        },
        relationships: {
          company: {
            links: {
              self: 'http://example.org/user_api/v1/farms/987614/relationships/company',
              related: 'http://example.org/user_api/v1/farms/987614/company',
            },
          },
          fields: {
            links: {
              self: 'http://example.org/user_api/v1/farms/987614/relationships/fields',
              related: 'http://example.org/user_api/v1/farms/987614/fields',
            },
          },
        },
      },
      987615: {
        id: '987615',
        type: 'farms',
        links: { self: 'http://example.org/user_api/v1/farms/987615' },
        attributes: {
          company_id: 987124,
          created_at: '2011-06-15T10:30:00.000+08:00',
          description: 'Vineyard',
          location: {
            number: null,
            street: null,
            suburb: null,
            city: null,
            county: null,
            state: 'Western Australia',
            postcode: null,
            country: 'Australia',
            latitude: -29.0779350143255,
            longitude: 133.665562768221,
          },
          name: 'Farm 1',
          reporting_region: 'Farm 1',
          updated_at: '2011-06-15T10:30:00.000+08:00',
        },
        relationships: {
          company: {
            links: {
              self: 'http://example.org/user_api/v1/farms/987615/relationships/company',
              related: 'http://example.org/user_api/v1/farms/987615/company',
            },
          },
          fields: {
            links: {
              self: 'http://example.org/user_api/v1/farms/987615/relationships/fields',
              related: 'http://example.org/user_api/v1/farms/987615/fields',
            },
          },
        },
      },
      987619: {
        id: '987619',
        type: 'farms',
        links: { self: 'http://example.org/user_api/v1/farms/987619' },
        attributes: {
          company_id: 987124,
          created_at: '2011-06-15T10:30:00.000+08:00',
          description: 'Pasture',
          location: {
            number: null,
            street: null,
            suburb: null,
            city: null,
            county: null,
            state: 'Western Australia',
            postcode: null,
            country: 'Australia',
            latitude: -29.0779350143255,
            longitude: 133.665562768221,
          },
          name: 'Farm 1',
          reporting_region: 'Farm 1',
          updated_at: '2011-06-15T10:30:00.000+08:00',
        },
        relationships: {
          company: {
            links: {
              self: 'http://example.org/user_api/v1/farms/987619/relationships/company',
              related: 'http://example.org/user_api/v1/farms/987619/company',
            },
          },
          fields: {
            links: {
              self: 'http://example.org/user_api/v1/farms/987619/relationships/fields',
              related: 'http://example.org/user_api/v1/farms/987619/fields',
            },
          },
        },
      },
    });
  }, 200 + 1000 * Math.random());
}

export function getFieldsForCompanyID(companyId, setFields) {
  setTimeout((companyId) => {
    // console.log(`This is a stub for getting Fields data. It ignored the companyID (${companyId})`);
    // This would find all farms with companyId, then find their fields
    setFields({
      987654: {
        id: '987654',
        type: 'fields',
        links: { self: 'http://example.org/user_api/v1/fields/987654' },
        attributes: {
          application_cost: null,
          area: null,
          boundary: null,
          chemical_cost: null,
          contractor_cost: null,
          created_at: '2011-06-15T10:30:00.000+08:00',
          crops: null,
          cropping_method: 'dryland',
          description: 'Potatoes',
          farm_id: 987613,
          fertilizer_cost: null,
          field_group_id: 987613,
          gross_margin: null,
          harvested_area: null,
          harvested_weight: null,
          harvest_date: null,
          irrigation: 'Pivot',
          name: 'Field 1',
          other_cost: null,
          other_income: null,
          plant_spacing: '15 cm',
          planting_date: null,
          row_spacing: '20 cm',
          season_id: null,
          seed_cost: null,
          updated_at: '2011-06-15T10:30:00.000+08:00',
          weatherStation: '',
          yield_price: null,
        },
        relationships: {
          farm: {
            links: {
              self: 'http://example.org/user_api/v1/fields/987654/relationships/farm',
              related: 'http://example.org/user_api/v1/fields/987654/farm',
            },
          },
        },
      },
      987655: {
        id: '987655',
        type: 'fields',
        links: { self: 'http://example.org/user_api/v1/fields/987655' },
        attributes: {
          application_cost: null,
          area: null,
          boundary: null,
          chemical_cost: null,
          contractor_cost: null,
          created_at: '2011-06-15T10:30:00.000+08:00',
          crops: null,
          cropping_method: 'dryland',
          description: 'Tomatoes',
          farm_id: 987613,
          fertilizer_cost: null,
          field_group_id: 987613,
          gross_margin: null,
          harvested_area: null,
          harvested_weight: null,
          harvest_date: null,
          irrigation: 'Pivot',
          name: 'Field 1',
          other_cost: null,
          other_income: null,
          plant_spacing: '15 cm',
          planting_date: null,
          row_spacing: '20 cm',
          season_id: null,
          seed_cost: null,
          updated_at: '2011-06-15T10:30:00.000+08:00',
          weatherStation: '',
          yield_price: null,
        },
        relationships: {
          farm: {
            links: {
              self: 'http://example.org/user_api/v1/fields/987655/relationships/farm',
              related: 'http://example.org/user_api/v1/fields/987655/farm',
            },
          },
        },
      },
      987656: {
        id: '987656',
        type: 'fields',
        links: { self: 'http://example.org/user_api/v1/fields/987656' },
        attributes: {
          application_cost: null,
          area: null,
          boundary: null,
          chemical_cost: null,
          contractor_cost: null,
          created_at: '2011-06-15T10:30:00.000+08:00',
          crops: null,
          cropping_method: 'dryland',
          description: 'Avocados',
          farm_id: 987614,
          fertilizer_cost: null,
          field_group_id: 987613,
          gross_margin: null,
          harvested_area: null,
          harvested_weight: null,
          harvest_date: null,
          irrigation: 'Pivot',
          name: 'Field 1',
          other_cost: null,
          other_income: null,
          plant_spacing: '15 cm',
          planting_date: null,
          row_spacing: '20 cm',
          season_id: null,
          seed_cost: null,
          updated_at: '2011-06-15T10:30:00.000+08:00',
          weatherStation: '',
          yield_price: null,
        },
        relationships: {
          farm: {
            links: {
              self: 'http://example.org/user_api/v1/fields/987656/relationships/farm',
              related: 'http://example.org/user_api/v1/fields/987656/farm',
            },
          },
        },
      },
      987657: {
        id: '987657',
        type: 'fields',
        links: { self: 'http://example.org/user_api/v1/fields/987657' },
        attributes: {
          application_cost: null,
          area: null,
          boundary: null,
          chemical_cost: null,
          contractor_cost: null,
          created_at: '2011-06-15T10:30:00.000+08:00',
          crops: null,
          cropping_method: 'dryland',
          description: 'Oranges',
          farm_id: 987614,
          fertilizer_cost: null,
          field_group_id: 987613,
          gross_margin: null,
          harvested_area: null,
          harvested_weight: null,
          harvest_date: null,
          irrigation: 'Pivot',
          name: 'Field 1',
          other_cost: null,
          other_income: null,
          plant_spacing: '15 cm',
          planting_date: null,
          row_spacing: '20 cm',
          season_id: null,
          seed_cost: null,
          updated_at: '2011-06-15T10:30:00.000+08:00',
          weatherStation: '',
          yield_price: null,
        },
        relationships: {
          farm: {
            links: {
              self: 'http://example.org/user_api/v1/fields/987657/relationships/farm',
              related: 'http://example.org/user_api/v1/fields/987657/farm',
            },
          },
        },
      },
      987658: {
        id: '987658',
        type: 'fields',
        links: { self: 'http://example.org/user_api/v1/fields/987658' },
        attributes: {
          application_cost: null,
          area: null,
          boundary: null,
          chemical_cost: null,
          contractor_cost: null,
          created_at: '2011-06-15T10:30:00.000+08:00',
          crops: null,
          cropping_method: 'dryland',
          description: 'Olives',
          farm_id: 987614,
          fertilizer_cost: null,
          field_group_id: 987613,
          gross_margin: null,
          harvested_area: null,
          harvested_weight: null,
          harvest_date: null,
          irrigation: 'Pivot',
          name: 'Field 1',
          other_cost: null,
          other_income: null,
          plant_spacing: '15 cm',
          planting_date: null,
          row_spacing: '20 cm',
          season_id: null,
          seed_cost: null,
          updated_at: '2011-06-15T10:30:00.000+08:00',
          weatherStation: '',
          yield_price: null,
        },
        relationships: {
          farm: {
            links: {
              self: 'http://example.org/user_api/v1/fields/987658/relationships/farm',
              related: 'http://example.org/user_api/v1/fields/987658/farm',
            },
          },
        },
      },
      987659: {
        id: '987659',
        type: 'fields',
        links: { self: 'http://example.org/user_api/v1/fields/987659' },
        attributes: {
          application_cost: null,
          area: null,
          boundary: null,
          chemical_cost: null,
          contractor_cost: null,
          created_at: '2011-06-15T10:30:00.000+08:00',
          crops: null,
          cropping_method: 'dryland',
          description: 'Sauvignon Blanc',
          farm_id: 987615,
          fertilizer_cost: null,
          field_group_id: 987613,
          gross_margin: null,
          harvested_area: null,
          harvested_weight: null,
          harvest_date: null,
          irrigation: 'Pivot',
          name: 'Field 1',
          other_cost: null,
          other_income: null,
          plant_spacing: '15 cm',
          planting_date: null,
          row_spacing: '20 cm',
          season_id: null,
          seed_cost: null,
          updated_at: '2011-06-15T10:30:00.000+08:00',
          weatherStation: '',
          yield_price: null,
        },
        relationships: {
          farm: {
            links: {
              self: 'http://example.org/user_api/v1/fields/987659/relationships/farm',
              related: 'http://example.org/user_api/v1/fields/987659/farm',
            },
          },
        },
      },
    });
  }, 200 + 1000 * Math.random());
}
